# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: FileCreate 
  steps: 
  - script: mkdir f2
  - script: touch f2/f2
  - script: ls -lart
  - script: pwd
  - task: S3Upload@1
    inputs:
      awsCredentials: 'AWS_SANDBOX'
      regionName: 'us-east-1'
      bucketName: 'azure-devops-1'
      sourceFolder: 'f2/index.html'
      globExpressions: '**'
